In [1]:
import numpy as np
x=np.array([[10,20,30],
           [40,50,60],
           [70,80,90]],dtype=complex)
x


array([[10.+0.j, 20.+0.j, 30.+0.j],
       [40.+0.j, 50.+0.j, 60.+0.j],
       [70.+0.j, 80.+0.j, 90.+0.j]])

In [2]:
y=np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
y=np.ones((3,2))
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
z=np.ones((3,3),dtype=[('m','int'),('n','float')])
z

array([[(1, 1.), (1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.), (1, 1.)]], dtype=[('m', '<i4'), ('n', '<f8')])

In [26]:
# traversing an array
import numpy as np
x=np.array([[10,20,30],
           [40,50,60],
           [70,80,90]])
for i in x:
    for j in i:
        print(j, end=" ") #to give saperation after each element
    print() #to print in next line

10 20 30 
40 50 60 
70 80 90 


In [11]:
print(x[2:3])

[[70 80 90]]


In [12]:
print(x[0:2])

[[10 20 30]
 [40 50 60]]


In [17]:
print(x[::-1])

[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [23]:
print(x[ :,2])

[30 60 90]


In [29]:
y=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

result=[]
for i in range(len(x)):
    row=[]
    for j in range(len(x[0])):
        row.append(x[i,j]+y[i,j])
    result.append(row)

result

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]

In [33]:
import numpy as pd
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
arr2=np.array([[10,20,30],[40,50,60],[70,80,90]])
result=np.transpose(arr1)
result

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])